travis:
  secure:
    BINSTAR_TOKEN: TV6O8BdeIwKGTZ6SZzhexHQCrdKtW2EUshhZHqfc+ssK7gBBLV1Z7Oa2bTKiRPGwaME89LemL8kTsrWrfYBAaUwaKDaYt012miEot/TJCwV+C9EAeywVQUiP/1Mz98j3yWulRB83hiX3UZEsYnjbkJFUmJpORQRVe36Pi2azESJUQG0FG+3uC76y344ivIYjSI1+4geHpMviaT73SqUKneJJne4Dd5BWaf/7wWADJ0WOgMC3x5VZeNTxIP8mE+QhBljcd5bHMLRnjaaGtWafldz4hHO9CEj9WdjL3cKxsMdcWD2rfT7bd1b6YAD9DRUarvfIhNB+aVWATnYypvvws5cG7GWd/22yfTCLTNhI9VrRomuZl+jGkNUMghKYWk7p1apZ2ytXxKe4O1lmkJFanaDFAZ977julVO1MqQTFu2O+nFUUq2bfDh+7tygPnPkZCI0jCbWIhxb/u8Mu6/3hkjIZQh4fKDeS746L6mS1kUtIgaeTAhZUQ9wYgBLO0ynddHHV2MhOBQEJUEkVaAqh6coCoTpp0PViqNMVD8NZOSpP/V3ccVMChghizcp9HG20zbzb52uUC1F9paAiK12vd5NckFtqmC34r38PkVJHoEoRzAbkIhXmp1KO6mCn81kpzNjnmyJoUZ/SGkJq15BWIh7JOgpr5RlyYGkODSPwtqE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
